package com.example.ddm.appui.greendao;

import com.example.ddm.appui.bean.dbbean.RecentCity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentCityDaoConfig;

    private final RecentCityDao recentCityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentCityDaoConfig = daoConfigMap.get(RecentCityDao.class).clone();
        recentCityDaoConfig.initIdentityScope(type);

        recentCityDao = new RecentCityDao(recentCityDaoConfig, this);

        registerDao(RecentCity.class, recentCityDao);
    }
    
    public void clear() {
        recentCityDaoConfig.clearIdentityScope();
    }

    public RecentCityDao getRecentCityDao() {
        return recentCityDao;
    }

}
