package com.example.ddm.appui.constant;
/**
 * Created by zzw .
 * Emile:1916973618@qq.com
 */
public interface Url {
//    String BaseUrl = "http://www.ddmzl.com";
    String link = "http://www.ddmzl.com/m/html/index.html?";
    //token=A4AAF2B09F28B31BB161FD8AFD5AAF89
    String BaseUrl = "http://192.168.3.55";
    String GetKey = BaseUrl + "/user/userLoginKey.json?";//获取key
    String Login = BaseUrl + "/user/userLogin.json?";//获得key进行加密登陆
//    String Send_Code = BaseUrl + "/user/sendMobileCode.json?";//发送验证码
    String IMAGEVERIFYC = BaseUrl + "/imageVerifyC/ifCode?";//验证手机号是否请求过验证码
    String Send_Code1 = BaseUrl + "/user/sendMobileCode_ValidateCode.json?";//没有token，获取验证码
    String Send_Code = BaseUrl + "/user/sendMobileCode_Vtoken.json?";//有token，获取验证码
    String validateCode = BaseUrl + "/imageVerifyC/validateCode?";//图片验证码
    String verifyCode = BaseUrl + "/imageVerifyC/verifyCode?";//检查图片验证码
    String DeviceDetail = BaseUrl + "/user/checkMobileCode.json?";//检查验证码
    String FINGCARD = BaseUrl + "/user/findPassword.json?";//找回密码
    String Note_Login =BaseUrl+"/user/userLogin2.json?";//短信验证通过登陆
    String Alter_Pwd = BaseUrl + "/user/updatePassword.json?";//修改登陆密码和交易密码
    String Alter_Name = BaseUrl + "/user/updateRealName.json?";//修改姓名
    String Alter_Sex = BaseUrl + "/user/updateSex.json?";//修改性别
    String Alter_Email = BaseUrl + "/user/updateEmail.json?";//修改邮箱
    String Alter_WeChat = BaseUrl + "/user/updateWeixin.json?";//修改微信
    String Alter_Status = BaseUrl + "/user/updateIdentity.json?";//修改身份号
    String Personal_Data = BaseUrl + "/user/info.json?";//个人资料
    String PERSONAL_PIC = BaseUrl + "/user/getUserHeadData.json?";//个人图像
    String Alter_Qq = BaseUrl + "/user/updateQQ.json?";//修改qq
    String Get_Address = BaseUrl + "/user/getAddress.json?"; //获取用户地址
    String Add_Address = BaseUrl + "/user/addOrUpdateAddress.json?";//添加或编辑用户地址
    String Add_Card = BaseUrl + "/cardC/addCard.json?";//添加银行卡
    String Compile_Card = BaseUrl + "/cardC/updateCard.json?";//编辑银行卡
    String New_SHOP = BaseUrl + "/shopC/queryNewShop.json?";//最新商家
    String CLASS_SHOP = BaseUrl + "/shopC/getCategoryById.json?";//分类接口
    String SHOP_HOT = BaseUrl + "/shopC/getPopShop.json?";//热门商家
    String SHOP_DETAIL = BaseUrl + "/shopC/ShopDetailed.json?";//商品详情
    String SHOPDETAILED = BaseUrl + "/shopC/shopDetailed_V2.json?";//店铺详情
    String My_Order = BaseUrl + "/zuoDanC/userOrderList.json?";//我的订单
    String ACCOUNTBEAN = BaseUrl + "/accountC/getAccountSurvey.json?";//账户概况
    String INFORM = BaseUrl + "/InformsC//getInformsList.json?";//通知
    String INFORM_DETAIL = BaseUrl + "/InformsC/getDetails.json?";//通知详情
    String WORK_ORDER = BaseUrl + "/zuoDanC/userZuoDanList.json?";//做单明细
    String WORKORDER = BaseUrl + "/zuoDanC/zuoDan.json?";//线下做单
    String APPLYORDER = BaseUrl + "/zuoDanC/zuoDanApply.json?";//做单申请
    String AUDITORDER = BaseUrl + "/zuoDanC/zuoDanShenHe.json?";//做单审核成功
    String AUDITORDERFAIL = BaseUrl + "/zuoDanC/rejectZuoDan.json?";//做单审核失败
    String FUNDWATER = BaseUrl + "/flowC/getUserFmsFlowV1.1.json?";//资金流水
    String DDETAIL = BaseUrl + "/flowC/getDingDangFlowV1.1.json?";//叮当明细
    String CHANGEPHONE = BaseUrl + "/user/checkTwoMobileCode.json?";//修改手机号
    String CARDLIST = BaseUrl + "/cardC/getCardList.json?";//获取银行卡
    String BANKCARD_DETAIL = BaseUrl + "/cardC/getOneCard.json?";//银行卡详情
    String GETNEWS = BaseUrl + "/messagesC/getUserMessages.json?";//获得用户消息
    String GETONENEWS = BaseUrl + "/messagesC/getOneMessages.json?";//获得用户消息详情
    String POSTPIC = BaseUrl + "/uploadImage.do";//上传图片
    String GETADDRESS = BaseUrl + "/user/getAddress.json?";//得到用户地址
    String READNEWS = BaseUrl + "/messagesC/updateNotReadMessages.json?";//修改消息为已读
    String CHECK = BaseUrl + "/user/checkUserisEmpty.json?";//做单验证手机号
    String APPLYORDERID = BaseUrl + "/zuoDanC/oneOrder.json?";//获取单个单子
    String HOT = BaseUrl + "/openSearchC/popSearch.json?city=";//热门搜索
    String ADD_RECENT = BaseUrl + "/user/updateAddressHistory.json?";//添加用户访问城市
    String GET_HOTCITY = BaseUrl + "/areaC/cityHot.json?";//获得最近访问的三个城市
    String GET_ALLCITY = BaseUrl + "/areaC/cityPosition.json";//获得全部城市
    String GET_RECENT = BaseUrl + "/user/getUserAddressHistory.json?";//获得最近访问的三个城市
    String GET_CITYDETAIL = BaseUrl + "/areaC/getAreaByName.json?";//获取城市里的区县
    String REGISTERUSER = BaseUrl + "/user/registerUser.json?";//验证码成功注册用户
    String ENTER = BaseUrl + "/shopC/customerShopApplicationAdd.json?";//入驻的接口
    String UNBINDTHISCARD = BaseUrl + "/cardC/unBindThisCard.json?";//解绑银行卡的接口
    String TOBEDEFAULT = BaseUrl + "/cardC/toBeDefault.json?";//指定银行卡为默认银行卡
    String RECHARGEC = BaseUrl + "/rechargeC/add.json?";//获得订单接口
    String SHOP_SUGGEST = BaseUrl + "/openSearchC/shopSuggest.json?";//商铺搜索
    String NEARBYSUGGEST = BaseUrl + "/openSearchC/nearbySuggest.json?";//附近搜索
    String GET_CATEGORY = BaseUrl + "/categoryC/getCategory.json?";//首页分类
    String SEARCH =BaseUrl +"/openSearchC/popSearch.json?";//热门搜索
    String SEARCHSHOPPING = BaseUrl+"/openSearchC/shopSearch.json?";//热门跳转
    String OPEN_SEARCH = BaseUrl + "/openSearchC/areaSuggest.json?";//城市搜索
    String NEWSNUM = BaseUrl + "/messagesC/countNotReadMessages.json?";//首页消息个数
    String WAITPAY = BaseUrl + "/rechargeC/queryCreate.json?";//待支付列表
    String TIXIANC = BaseUrl + "/tiXianC/addTiXianShenQing.json?";//积分兑换
    String TIXIAN = BaseUrl + "/tiXianC/getTiXianFactorage.json?";//提现详情
    String EXCHANGEBEAN = BaseUrl + "/tiXianC/userGetTiXianShenQingList.json?";//兑换明细
    String VERSION = BaseUrl +"/user/appVersion.json";//判断版本号
    String UPDAPE = BaseUrl +"/zl.apk";//更新
    String SHENGFENG = BaseUrl + "/areaC/province.json";//省份接口
    String DOWNTOWN = BaseUrl + "/areaC/getCity.json?";//provinceId=5市接口
    String COUNTY = BaseUrl + "/areaC/getArea.json?";//cityId=33县区接口
    String PIC = BaseUrl + "/user/updateAvtor.json?";//上传图片
    String HONGBAO = BaseUrl + "/user/getUserIntegral.json?";//积分
    String HONGBAOSURE = BaseUrl + "/user/UpdateUserIntegral.json?";//确定红包已收
    String MAINTAIN = BaseUrl + "/appC/mainTainSwitch.json";//系统维护
    String GETQRCODE = BaseUrl + "/transferC/getQrcode.json?";//获取商家id
    String GETSHOP = BaseUrl + "/transferC/getShop.json?";//转账人的详情
    String TRANSFER = BaseUrl + "/transferC/transfer.json?";//确认转账
    String MYCODE = BaseUrl + "/qrcodeC//encode/";//我的二维码
    String TRANSFERC = BaseUrl + "/transferC/search.json?";//转账记录
    String RECEIPT = BaseUrl + "/transferC/searchme.json?";//收款记录
    String GETUSERTYPE = BaseUrl + "/user/getUserType.json?";//获取用户等级
    String GETUSERID = BaseUrl + "/user/getUserId.json?";//获取用户id
    String QRCODEC = BaseUrl + "/qrcodeC/encodeApp/";//获取用户邀请码
    String BANNERC = BaseUrl + "/bannerC/appSixBanner.json";//轮播图
    String SHARE = BaseUrl + "/m/html/shop_detail.html?shopId=";//分享后跳转的界面
    String SHOWREDISMESSAGE = BaseUrl + "/messagesC/showRedisMessage.json?";//商城首页滚动消息
    String SENDMOBILECODE = BaseUrl + "/user/sendMobileCode_v2.json?";//邀请验证码
    String CHECKMOBILECODE = BaseUrl + "/user/checkMobileCode_v2.json?";//邀请验证验证码
    String REGISTER = BaseUrl + "/user/register.json?";//邀请注册
    String GOODSC = BaseUrl + "/goodsC/receptionDetails?";//商品详情
    String CHARGE = BaseUrl + "/ali/payApp.do?";//支付接口
    String COMMENTSC = BaseUrl + "/commentsC/getCommentsList.json?";//用户评价
    String COMMENTSSUMDATAS = BaseUrl + "/commentsC/commentsSumdatas.json?";//用户评价
    String GETREGISTERREDPACKET = BaseUrl + "/user/getRegisterRedPacket.json?";//注册红包
    String UPDATEREGISTERREDPACKET = BaseUrl + "/user/updateRegisterRedPacket.json?";//领取注册红包
    String SHOPPINGCARTC = BaseUrl + "/ShoppingCartC/getUserShoppingCart.json?";//购物车列表
    String modifyUserShoppingCart = BaseUrl + "/ShoppingCartC/modifyUserShoppingCart.json?";//修改购物车
    String deleteUserShoppingCart = BaseUrl + "/ShoppingCartC/deleteUserShoppingCart.json?";//删除商品
    String GETSPECIFICATION = BaseUrl + "/specificationC/getSpecification.json?";//商品规格
    String GETGOODSPECIFICATION = BaseUrl + "/goodSpecificationC/getGoodSpecification.json?";//商品规格详情
    String GETUSERSHOPPINGCART = BaseUrl + "/ShoppingCartC/getUserShoppingCart.json?";//查询购物车
    String optionCart = BaseUrl + "/ShoppingCartC/optionCart.json?";//选择购物车
    String addUserShoppingCart = BaseUrl + "/ShoppingCartC/addUserShoppingCart.json?";//加入购物车
    String getUserAddress = BaseUrl + "/user/getUserAddress.json?";//获取用户收货地址列表
    String deleteUserAddress = BaseUrl + "/user/deleteUserAddress.json?";//删除收货地址
    String userAddressToBeDefault = BaseUrl + "/user/userAddressToBeDefault.json?";//指定默认收货地址
    String addUserAddress = BaseUrl + "/user/addUserAddress.json?";//添加用户地址
    String editUserAddress = BaseUrl + "/user/editUserAddress.json?";//编辑用户地址
    String getDefault = BaseUrl + "/user/getDefault.json?";//获取默认收货地址
    String submitOrder = BaseUrl + "/zuoDanC/submitOrder.json?";//购物车确认订单
    String confirmOrder = BaseUrl + "/zuoDanC/confirmOrder.json?";//单个商品结算
    String daZhuangPanMessage = BaseUrl + "/activityC/daZhuangPanMessage.json?";//大转盘
    String rollMessage2 = BaseUrl + "/activityC/rollMessage2.json";//大转盘中奖消息
    String slyderAdventures = BaseUrl + "/activityC/slyderAdventures.json?";//抽奖
    String userGetJiangPin = BaseUrl + "/zongJiangRecordC/userGetJiangPin?";//领取奖品
    String userPurchaseOrderList = BaseUrl + "/zuoDanC/userPurchaseOrderList.json?";//用户订单列表
    String cancelOrder = BaseUrl + "/zuoDanC/cancelOrder.json?";//取消订单
    String delZuoDan = BaseUrl + "/zuoDanC/delZuoDan.json?";//删除订单
    String receiptOrder = BaseUrl + "/zuoDanC/receiptOrder.json?";//确认收货
    String userOrderDetail = BaseUrl + "/zuoDanC/userOrderDetail.json?";//订单详情
    String getZongJiangRecord = BaseUrl + "/zongJiangRecordC/getZongJiangRecord?";//中奖记录
    String searchUserCoupon = BaseUrl + "/userCouponC/searchUserCoupon.json?";//满减优惠券查询
    String getCouponNumber = BaseUrl + "/userCouponC/getCouponNumber.json?";//优惠券数量查询
    String encode = BaseUrl + "/qrcodeC/encode/";//卡券二维码
    String getCommission = BaseUrl + "/commissionC/getCommission.json?";//分享流水
    String addComments = BaseUrl + "/commentsC/addComments.json?";//添加评论
    String getDetailCommission = BaseUrl + "/commissionC/getDetailCommission.json?";//分享流水详情
    String shareTeam = BaseUrl + "/lowerC/shareTeam.json?";//扇形图
    String NEARBY = "http://yuntuapi.amap.com/datasearch/around?key=dc6c7273b5c4084233dc566d71893688&center=113.686768,34.795123&radius=50000&tableid=599d2769afdf521e86da5a76";//附近商家的接口
}
